# Generated by Django 5.1 on 2024-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
