# Generated by Django 5.1 on 2024-08-10 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niut', '0002_alter_item_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='onhover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onhover', to='niut.image'),
        ),
    ]
