# Generated by Django 5.1 on 2024-08-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niut', '0003_alter_image_file_alter_item_onhover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='onhover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niut.image'),
        ),
    ]
