# Generated by Django 5.1 on 2024-08-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niut', '0004_alter_item_onhover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='onhover',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cover',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(default='/media/', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
